version: '3'
services:
 mongo:
  image: mongo:latest
  ports:
   - "27017:27017"
  volumes:
   - ./data:/data/db
 api:
  build: server/
  ports:
   - "5000:5000"
  links:
   - mongo
  depends_on:
   - "mongo"
  command: ["./wait-for-it.sh", "mongo:27017", "--","node", "./server.js"]
 client:
  build: client/
  ports: 
   - "3000:3000"
  links:
   - api
  command: ["serve", "-s", "./build"] 
