version: '3'
services:
 mongo:
  image: mongo:latest
  container_name: mongodb
  restart: always
  environment:
   MONGO_INITDB_DATABASE: mernProject
  ports:
   - "27017:27017"
  volumes:
   - ./data:/data/db
 api:
  build: server/
  ports:
   - "5000:5000"
  links:
   - mongo
  depends_on:
   - "mongo"
  volumes: 
   - /usr/share/nginx/html/img:/app/routes/public/img/
   - ./api-logs:/logs
  command: ["./wait-for-it.sh", "mongo:27017", "--","node", "./server.js"]
 client:
  build: client/
  ports: 
   - "3000:3000"
  links:
   - api
  volumes:
   - /usr/share/nginx/html/img:/app/build/img/
  command: ["serve", "-s", "/app/build"]
